plugins {
    id 'org.springframework.boot' version "4.1.0"
    id 'application'
}

java {
    sourceCompatibility = 25
    targetCompatibility = 25
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':lib:ac-swt-common')

    implementation("org.eclipse.platform:org.eclipse.swt.gtk.linux.aarch64:3.134.0") {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
}

tasks.register("copyDependencies", Copy) {
    from(configurations.runtimeClasspath).into(layout.buildDirectory.dir("jars"))
}
tasks.register("copyJar", Copy) {
    from(tasks.jar).into(layout.buildDirectory.dir("jars"))
}
build.dependsOn("copyDependencies", "copyJar")

application {
    mainClass = 'com.webcodepro.applecommander.ui.swt.SwtAppleCommander'
}

bootJar {
    archiveBaseName = 'AppleCommander'
    archiveAppendix = 'linux-aarch64'
    manifest {
        attributes 'Implementation-Title': 'AppleCommander (Linux Arm)',
                   'Implementation-Version': archiveVersion
    }
    from('../../LICENSE')
}
