plugins {
    id 'java-library'
}

java {
    sourceCompatibility = 25
    targetCompatibility = 25
}

repositories {
    mavenCentral()
    flatDir {
        // Raspberry Pi 32-bit library
        dirs project(':').projectDir.absolutePath + "/swt-lib"
    }
}

dependencies {
    implementation project(':lib:ac-api')

    implementation "net.sf.applecommander:applesingle-api:1.2.2"
    implementation "org.applecommander:bastools-api:5.0"

    testImplementation platform("org.junit:junit-bom:6.1.2")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "org.apache.commons:commons-lang3:3.20.0"
}

test {
    useJUnitPlatform()
    String osName = System.getProperty('os.name').toLowerCase().split()[0]
    String osArch = System.getProperty('os.arch').toLowerCase().split()[0]
    switch (osArch) {
        case 'amd64':
            osArch = "x86_64"
            break
        case 'arm':
            swtVersion = "3.8.2"
            break
    }
    String swtDependency
    switch (osName) {
        case 'windows':
            swtDependency = "org.eclipse.platform:org.eclipse.swt.win32.win32.${osArch}:3.134.0"
            break
        case 'linux':
            swtDependency = "org.eclipse.platform:org.eclipse.swt.gtk.linux.${osArch}:3.134.0"
            break
        case 'mac':
            swtDependency = "org.eclipse.platform:org.eclipse.swt.cocoa.macosx.${osArch}:3.134.0"
            break
        default:
            throw new Exception('Unknown OS')
    }
    dependencies {
        compileOnly("$swtDependency") {
            exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
        }
        testImplementation("$swtDependency") {
            exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
        }
    }
}

jar {
    archiveBaseName = 'AppleCommander'
    archiveAppendix = 'swt-common'
}
