plugins {
    id 'java-library'
}

java {
    sourceCompatibility = 25
    targetCompatibility = 25
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':app:cli-ac')
    implementation project(':lib:ac-api')
    compileOnly "org.apache.ant:ant:$antVersion"

    testImplementation platform("org.junit:junit-bom:$junitVersion")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "org.apache.ant:ant:$antVersion"
}

test {
    if (System.getenv("AC_BACKUP_STRATEGY") != null) {
        throw new GradleException("Ant tests fail if AC_BACKUP_STRATEGY is set!")
    }
    useJUnitPlatform()
}

jar {
    archiveBaseName = 'AppleCommander'
    archiveAppendix = 'ant'
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}

// Automagically run the Ant tests as part of the build process.
// See: https://docs.gradle.org/current/userguide/ant.html
ant.importBuild('src/test/resources/build-testacant.xml') { antTargetName ->
    'anttest-' + antTargetName
}
tasks.named('test') {
    finalizedBy('anttest-all')
}
